### ISSUE TITLE
复制编辑器内的内容再粘贴到编辑器中出现多余空行

### ISSUE THREAD

**Issue by Ron233** [EthanYan6/quill-image-super-solution-module#5]
# bug:使用插件时，复制编辑器内的内容再粘贴到编辑器中时,每行回车后面都多了 一行空行 <p></br></p>
## 复现步骤
1.  可使用示例代码复现
2.  在富文本编辑器内输入几行文本，每行回车
3.  全选复制编辑器内的文本，再粘贴回编辑器内

## 期望效果
回车换行重新复制粘贴到编辑器内不会出现多余的空行

## 复现环境
Chrom浏览器 87.0.4280.66（正式版本）

**Comment by EthanYan6** [comment]
很抱歉刚看到你的问题，这目前是个 `bug`，我会纳入下个版本修改。由于最近工作太忙，暂不确定下个版本时间，抱歉。

**Comment by EthanYan6** [comment]
您好，目前已更新。您可以从 GitHub 拉取最新代码或者 npm 安装最新版本即可使用。本 issue 在解决之后将关闭。如有疑问，欢迎再次留言。如果好用的话，希望多向他人推荐一下，谢谢。
